---
kind: pipeline
type: docker
name: default

trigger:
  ref:
    - refs/heads/aws
    - refs/heads/trunk
    - refs/pull/**
    - refs/tags/**

volumes:
    - name: docker_sock
      host:
        path: /var/run/docker.sock
    - name: root_home
      host:
        path: /root

steps:
  - name: build
    image: 324181518966.dkr.ecr.us-west-2.amazonaws.com/docker-builder:1
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
      - name: root_home
        path: /root
    
    commands:
      - make build
      - make push
      
      
