#!/bin/sh

set -eux

if [ -z "$NOMAD_PORT_http" ]; then UCM_PORT=26117; else UCM_PORT="$NOMAD_PORT_http" ; fi
export UCM_PORT

nginx
env UCM_HOST='*' UCM_TOKEN=sekret /usr/local/bin/ucm headless +RTS -N
